/* eslint-disable @next/next/no-page-custom-font */
import Sidebar from '@/components/sidebar/Sidebar';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <link
          rel="preconnect"
          href="https://fonts.googleapis.com"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Unbounded:wght@500&display=swap"
          rel="stylesheet"
        />
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <main></main>
    </>
  );
}
